mdss: rotator: Adapt kthread workqueue for 4.9
After commit b1cd6ab5b32f3af21effd37a4bfa521955c5f2fb, some of kthread workqueue that was picked
from 3.18 are get problem with implicit declaration of some function.

Current solution for now, is following and adapt function name to symlink with this 4.9 changes.

Changed code:
* queue_kthread_work -> kthread_queue_work
* init_kthread_worker -> kthread_init_worker
* init_kthread_work -> kthread_init_work
* flush_kthread_work -> kthread_flush_work

Compilation issue:
../drivers/video/fbdev/msm/mdss_rotator.c:863:3: error: implicit declaration of function 'init_kthread_worker' [-Werror,-Wimplicit-function-declaration]
                init_kthread_worker(&mgr->queues[i].worker);
                ^
../drivers/video/fbdev/msm/mdss_rotator.c:1041:3: error: implicit declaration of function 'queue_kthread_work' [-Werror,-Wimplicit-function-declaration]
                queue_kthread_work(&queue->worker, &entry->commit_work);
                ^
../drivers/video/fbdev/msm/mdss_rotator.c:1550:3: error: implicit declaration of function 'init_kthread_work' [-Werror,-Wimplicit-function-declaration]
                init_kthread_work(&entry->commit_work,
                ^
../drivers/video/fbdev/msm/mdss_rotator.c:1603:3: error: implicit declaration of function 'flush_kthread_work' [-Werror,-Wimplicit-function-declaration]
                flush_kthread_work(&entry->commit_work);
                ^
4 errors generated.

Signed-off-by: Dicky Herlambang <herlambangdicky5@gmail.com>
Signed-off-by: Hadad <repo-sync@outlook.com>